### ISSUE TITLE
Linux cli usage

### ISSUE THREAD

**Issue by C00reNUT** [Sirosky/Upscale-Hub#1]
Hello, 

I am not very familiar with video SR space, don't you know by any chance some linux based repo i could use to run these models through the command line?

Thank you!

**Comment by Sirosky** [comment]
As in you want to run upscaling models? [ChaiNNer](https://github.com/chaiNNer-org/chaiNNer) works on Linux, and has basic CLI support. If you're looking to train, [neosr](https://github.com/muslll/neosr) was developed on Linux, but also can be used to run models (and also has CLI support).
