### ISSUE TITLE
[REQUEST] glsl shaders

### ISSUE THREAD

**Issue by Bercraft** [Sirosky/Upscale-Hub#2]
Hi your work is great could you please release the glsl versions  of this shaders: 
1x_AniScale2_Refiner_10K, 
2x_AniScale2_ESRGAN_i16_110K, 
2x_AniScale2_ESRGAN_Lite_i16_165K.
So using vapoursynth with libplacebo makes it possible to use them on "every" architecture.
it would be great also a 1x of Ani4k V2 and of OpenProteus.
Thank you for your work.

**Comment by Sirosky** [comment]
Hi! Thanks for your interest. Unfortunately, it won't be possible. Training shader "versions" of a model is in reality training a completely different model with a different dataset. The GLSL models actually use a much smaller version of the original dataset, and I don't have plans to create GLSL versions of AniScale 2.

As for 1x models, the scale of the model is determined at time of training / dataset creation, so creating a 1x version of a model would also require a new dataset. In addition, I find that general-purpose 1x models tend to be worse at detail retention, so I prefer going 2x and downscaling with a kernel instead. 1x models are good for single purposes like removing h264 compression, but Ani4K v2 / OpenProteus are more general purpose.

**Comment by Bercraft** [comment]
I understand,thank you.
