### ISSUE TITLE
Model is changing aspect ratio for some reason?

### ISSUE THREAD

**Issue by Fotzkopf** [Sirosky/Upscale-Hub#3]
Hi, I really like the 2x AniSD RealPLKSR Models. Tried them out on a bunch of different sources and definitely like the results a lot, especially compared to other upscalers. However, there is one big problem.

No matter what I do, the aspect ratio is changed from the original 4:3. The image gets stretched and elongated.

This happens:

- No matter the specific source material.
- With both VideoJaNai and chaiNNer
- Also, when I apply padding to make it 16:9, it does not make a difference. Still stretching.

But it does not happen when upscaling images. Only video.
Any insights as to why that might be the case? Should I just upscale every frame seperately?

**Comment by Sirosky** [comment]
The models will only multiply the input source resolution, such as 2x. It won’t change aspect ratio. If you input a 32x32 image, it’ll output 64x64. 

There may be some weird aspect ratio metadata stuff going on, that’s causing the aspect ratio to be changed (whether in the source or the output). I’d definitely check that and your ffmpeg settings.

**Comment by Fotzkopf** [comment]
For anyone googling this: It was indeed wrong meta data. Turns out not every pixel is a square. Explicitly setting the aspect ratio to 4:3 while keeping resolution x2 of the original in ffmpeg resolved the issue.
